services:
  balanca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balanca
    restart: always
  
    # network_mode: host permite acesso direto às portas do host
    # Portas 80 (HTTP) e 81 (WebSocket) ficam disponíveis automaticamente
    network_mode: host

    # Dispositivo serial (ajuste para ttyACM0 se necessário)
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

    environment:
      SERIAL_PORT: "/dev/ttyUSB0"
      SERIAL_BAUD: "921600"
      WS_PORT: "81"
      HTTP_PORT: "80"

    # Monta o repositório em /app (read-only)
    volumes:
      - ./:/app:ro

    # Define /app/data como diretório de trabalho (onde estão os arquivos web)
    working_dir: /app/data

    # Executa o servidor Python
    command: ["python", "/app/server.py"]

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"