services:
  balanca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balanca
    restart: always
    depends_on:
      - db
    mem_limit: 512m
    ports:
      - "80:80"
      - "81:81"

    # Dispositivo serial (ajuste para ttyACM0 se necessário)
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

    # Capacidade de ajustar hora do sistema
    cap_add:
      - SYS_TIME

    environment:
      SERIAL_PORT: "/dev/ttyUSB0"
      SERIAL_BAUD: "921600"
      WS_PORT: "81"
      HTTP_PORT: "80"
      MYSQL_HOST: "db"
      MYSQL_USER: "balanca_user"
      MYSQL_PASSWORD: "balanca_password"
      MYSQL_DB: "balanca_gfig"
      MYSQL_ROOT_PASSWORD: "Hilquias"
      TZ: "America/Sao_Paulo"

    volumes:
      - ./:/app

    working_dir: /app/data

    command: ["python", "/app/server.py"]

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - balanca_network

  db:
    image: mariadb:11
    container_name: balanca_mysql
    restart: always
    mem_limit: 256m  # Limite de memória para o MySQL
    mem_reservation: 128m  # Memória reservada mínima
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password"
      MYSQL_DATABASE: "balanca_gfig"
      MYSQL_USER: "balanca_user"
      MYSQL_PASSWORD: "balanca_password"
      TZ: "America/Sao_Paulo"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - db_root_password
    ports:
      - "3306:3306"
    networks:
      - balanca_network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u balanca_user -p'balanca_password' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  balanca_network:
    driver: bridge

volumes:
  mysql_data:

secrets:
  db_root_password:
    file: ./db_root_password.txt
