version: '3.8'

services:
  balanca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balanca
    restart: always
    depends_on:
      - db
    mem_limit: 512m # NEW: Add memory limit
    ports:
      - "80:80"
      - "81:81"

    # Dispositivo serial (ajuste para ttyACM0 se necessário)
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

    # Capacidade de ajustar hora do sistema
    cap_add:
      - SYS_TIME

    environment:
      SERIAL_PORT: "/dev/ttyUSB0"
      SERIAL_BAUD: "921600"
      WS_PORT: "81"
      HTTP_PORT: "80"
      MYSQL_HOST: "db" # Nome do serviço MySQL no Docker Compose
      MYSQL_USER: "balanca_user"
      MYSQL_PASSWORD: "balanca_password"
      MYSQL_DB: "balanca_gfig"
      MYSQL_ROOT_PASSWORD: "Hilquias"
      TZ: "America/Sao_Paulo" # Timezone GMT-3

    # dns: - 1.1.1.1 removed

    # Monta o repositório em /app (read-only)
    volumes:
      - ./:/app

    # Define /app/data como diretório de trabalho (onde estão os arquivos web)
    working_dir: /app/data

    # Executa o servidor Python
    command: ["python", "/app/server.py"]

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - balanca_network

  db:
    image: mariadb:11
    container_name: balanca_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password"
      MYSQL_DATABASE: "balanca_gfig"
      MYSQL_USER: "balanca_user"
      MYSQL_PASSWORD: "balanca_password"
      TZ: "America/Sao_Paulo" # Timezone GMT-3
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - db_root_password
    ports:
      - "3306:3306" # Expor a porta do MySQL para acesso externo, se necessário
    networks:
      - balanca_network # Adiciona o serviço 'db' à rede interna
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u balanca_user -p'balanca_password'"]
      interval: 2s
      timeout: 10s
      retries: 30

  # phpmyadmin: (COMENTADO PARA PRODUÇÃO)
  #   image: phpmyadmin/phpmyadmin
  #   container_name: balanca_phpmyadmin
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     PMA_HOST: db # Connects to the 'db' service
  #     MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/db_root_password" # Use the same root password secret
  #     TZ: "America/Sao_Paulo" # Timezone GMT-3
  #     # PMA_USER: balanca_user # Optional: if you want to log in directly with the app user
  #     # PMA_PASSWORD: balanca_password # Optional: if you want to log in directly with the app user
  #   ports:
  #     - "8080:80" # Access PhpMyAdmin on port 8080
  #   secrets:
  #     - db_root_password
  #   networks:
  #     - balanca_network

networks:
  balanca_network:
    driver: bridge

volumes:
  mysql_data:

secrets:
  db_root_password:
    file: ./db_root_password.txt