services:
  balanca:
    build:
      context: ..                      # <- contexto = raiz do repo (balancaGFIG)
      dockerfile: balancaDocker/Dockerfile
    container_name: balanca
    restart: unless-stopped
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      SERIAL_PORT: "/dev/ttyUSB0"
      SERIAL_BAUD: "921600"
      WS_PORT: "81"
      HTTP_PORT: "8080"
      GIT_REPO: "https://github.com/rbeninca/balancaGFIG"
      GIT_BRANCH: "balança_serial"
      PULL_INTERVAL: "120"
      WEB_DIRECTORY: "/app/data"
    ports:
      - "8080:8080"
      - "81:81"
